server:
  port: 9999
  # 配置静态资源启用 gzip 压缩
  compression:
    enabled: true
    min-response-size: 128
# 配置主数据源
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://172.31.252.117:3306/qademo?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: qademo
    password: qademo
    #  data:
    # 配置mongo数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    mongodb:
  #      host: localhost
  #      port: 27017
  #      database: magicapi
  #      username: magicapi
  #      password: 123456
  # 配置redis数据源
#  redis:
#    host: localhost
#    port: 6379
#    database: 4
#    timeout: 5000


