server:
  port: 9999
  # 配置静态资源启用 gzip 压缩
  compression:
    enabled: true
    min-response-size: 128
# 配置主数据源
spring:
  neo4j:
    uri: bolt://localhost:7687/
    authentication:
      username: neo4j
      password: hy1996128
  datasource:
    url: jdbc:mysql://172.31.252.117:3306/qademo?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: qademo
    password: qademo
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    mongodb:
  #      host: localhost
  #      port: 27017
  #      database: magicapi
  #      username: magicapi
  #      password: 123456
  # 配置redis数据源
#  redis:
#    host: localhost
#    port: 6379
#    database: 4
#    timeout: 5000


